---
title: "Seu título aqui"
author: "Seu nome"
output: html_document
---

O seu relatório deve (ao menos) responder as seguintes perguntas:

1. Qual o mês do ano com o maior número de filmes? E o dia do ano?

2. Qual o top 5 países com mais filmes na base?

3. Liste todas as moedas que aparecem nas colunas `orcamento` e `receita` da
base `imdb_completa`.

4. Considerando apenas orçamentos e receitas em dólar ($), qual o gênero com
maior lucro? E com maior nota média?

5. Dentre os filmes na base `imdb_completa`, escolha o seu favorito. Então faça
os itens a seguir:

  a) Quem dirigiu o filme? Faça uma ficha dessa pessoa: idade (hoje em dia ou
  data de falecimento), onde nasceu, quantos filmes já dirigiu, qual o lucro
  médio dos filmes que dirigiu (considerando apenas valores em dólar) e outras
  informações que achar interessante (base `imdb_pessoas`).

  b) Qual a posição desse filme no ranking de notas do IMDB? E no ranking de
  lucro (considerando apenas valores em dólar)?

  c) Em que dia esse filme foi lançado? E dia da semana? Algum outro filme foi
  lançado no mesmo dia? Quantos anos você tinha nesse dia?

  d) Faça um gráfico representando a distribuição da nota atribuída a esse filme
  por idade (base `imdb_avaliacoes`).

```{r}
remotes::install_github("curso-r/basesCursoR")
imdb <- basesCursoR::pegar_base("imdb_completa")
imdb_pessoas <- basesCursoR::pegar_base("imdb_pessoas")
imdb_avaliacoes <- basesCursoR::pegar_base("imdb_avaliacoes")
```
